---
title: "Obversações Resultados da Utilização da Produtiva"
author: "Jhemeson Mota"
date: "13 de Junho de 2021"
output:
  html_document:
    highlight: pygments
  pdf_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(dplyr)
library(ggplot2)
```
* * *

**Carrega os dados do CSV para o DataFrame:**

```{r}
time1 <- read.csv(file="time1.csv", header=TRUE, sep=",")
time2 <- read.csv(file="time2.csv", header=TRUE, sep=",")
```

## Gráficos:

#### 1 - Evolução do Time 1 Ao Longo de 8 Semanas

```{r}

ggplot(data = time1, aes(y = produtividade, x = semana)) +
  geom_bar(stat = "identity", fill = "#0862A4")


```

#### 2 - Evolução do Time 2 Ao Longo de 8 Semanas

```{r}

ggplot(data = time2, aes(y = produtividade, x = semana)) +
  geom_bar(stat = "identity", fill = "#0862A4")

```

**Carrega os dados do CSV para o DataFrame:**

```{r}
time1Aval <- read.csv(file="time1Aval.csv", header=TRUE, sep=",")
time2Aval <- read.csv(file="time2Aval.csv", header=TRUE, sep=",")
```

#### 3 - Avaliação do Time 1

```{r}

ggplot(data = time1Aval, aes(y = valor, x = q)) +
  geom_bar(stat = "identity", fill = "#0862A4")


```

#### 4 - Avaliação do Time 2

```{r}

ggplot(data = time2Aval, aes(y = valor, x = q)) +
  geom_bar(stat = "identity", fill = "#0862A4")


```